export interface Response1 {
    name: string | null,
    priceToEarnings: string | null,
    pegRatio: string | null,
    priceToBook: string | null,
    debtToEquity: string | null,
    roe: string | number | null,
    exchange: string | null,
    country: string | null,
    sector: string | null,
    industry: string | null,
    yearHigh: string | null,
    yearLow: string | null,
    fiftyDayMA: string | null,
}